apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
    name: letencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: 'loesak.b@gmail.com'
        privateKeySecretRef:
            name: letsencrypt-prod
        http01: {}
